name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Clone Github Repo Action
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'career-opz'
        repository: 'commons'
        access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
            
    - name: Access cloned repository content
      run: |
        cd commons
        mvn clean install

    - name: Build with Maven
      run: mvn clean install -DskipTests
